baseURL = "https://learncodestream.github.io"
languageCode = "en-gb"
title = "Learn Code Stream"
theme = "hugo-geekdoc"
googleAnalytics = "G-NN4VBNXV6M" 

# Required to get well formatted code blocks
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9
[params]
    geekdocLogo = "images/vra-code-stream-logo.png"